[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/auth-steam-login"
  status = 302
  force = true

[[redirects]]
  from = "/logout"
  to = "/.netlify/functions/auth-logout"
  status = 302
  force = true

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/api-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/manual"
  to = "/.netlify/functions/api-manual"
  status = 200
  force = true

[[redirects]]
  from = "/api/links"
  to = "/.netlify/functions/api-links"
  status = 200
  force = true

[[redirects]]
  from = "/api/fortnite"
  to = "/.netlify/functions/api-fortnite"
  status = 200
  force = true

[[redirects]]
  from = "/api/lol"
  to = "/.netlify/functions/api-lol"
  status = 200
  force = true
